### ISSUE TITLE
Pin WR_PR

### ISSUE THREAD

**Issue by FrankSmith82** [xelalexv/oqtadrive#22]
the pin 2B (WR_PR) ,in the Ql diagram, is not connected so where should it be connected? Arduino D6 to what?

**Comment by xelalexv** [comment]
There's no specific QL diagram. Are you referring to the [project's diagram here](https://github.com/xelalexv/oqtadrive/blob/master/doc/schematic.png)? This sows D6 connected to `WR_PR` via a 2k2 resistor and diode (`D6 o---| 2k2 |--- >| ---o WR_PR`).

**Comment by TomDDG** [comment]
If you are using the edge connector just wire up as per the project diagram. If directly connecting to the motherboard then I'm not sure there is a WR_PR pin on the QL. This is how I wire it up
![image](https://user-images.githubusercontent.com/22009656/168883800-5178c524-2d01-423c-a24a-40ee3dc93ca5.png)

**Comment by xelalexv** [comment]
Thanks @TomDDG for replying! Now that you mention it, I remember that -in contrast to the Specturm- write protection on the QL is completely handled within each Microdrive unit, and the `WR_PR` signal is not carried in the Microdrive bus on the QL. So when building an OqtaDrive adapter exclusively for the QL, you don't need to connect `D6` from the Arduino. If you want to use the adapter also with a Spectrum, you need to connect it to `2B`, which won't hurt the QL since that pin is simply not used there.

**Comment by FrankSmith82** [comment]
Thanks guys !!
